// nalanda_desktop/src/renderer/src/Components/Dashboard/Header.jsx
import Navigator from "./Navigation"
import nalandaLogo from '../../assets/logo.svg'

function Header({title="Nalanda", slogan="Your Personal Document Assistant"}) {
    return (
        <div className="container md:mx-auto shadow-md bg-slate-300 dark:bg-slate-700 mb-5 pt-5">
            <header className="container md:mx-auto text-center justify-center items-center">
                <h1 className="text-4xl font-medium flex text-center justify-center items-center">
                    <img src={nalandaLogo} width="40" height="40" className="mr-2"/>
                    {title}
                </h1>
                <p className="italic">
                    {slogan}
                    <br />
                </p>
            </header>
            <Navigator/>
        </div>
    )
}

export default Header

// frontend/workspace/src/components/Header.vue
<template>
    <div class="container md:mx-auto shadow-md bg-gray-300 dark:bg-gray-700 mb-5 pt-5">
        <header class="container text-center">
            <h1 class="text-4xl font-medium">Nalanda</h1>
            <p>
                <i>The Open Library</i><br />
            </p>
        </header>
        <ul class="container md:mx-auto p-6 items-center justify-center md:flex">
            <li class="mr-1 bg-white inline-block py-2 px-4 mt-0.5 mb-0.5 text-slate-600 hover:text-slate-800 font-semibold rounded-md">
                <router-link to="/">
                    Home
                </router-link>
            </li>
            <li class="mr-1 bg-white inline-block py-2 px-4 mt-0.5 mb-0.5 text-slate-600 hover:text-slate-800 font-semibold rounded-md">
                <router-link to="/login">
                    Login
                </router-link>
            </li>
            <li class="mr-1 bg-white inline-block py-2 px-4 mt-0.5 mb-0.5 text-slate-600 hover:text-slate-800 font-semibold rounded-md">About Us</li>
        </ul>
    </div>
</template>
